name: Inference Pipeline

on:
  push:
    branches:
      - inference_branch

jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Add current directory to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run tests
        run: pytest tests/

  Train-Model:
    runs-on: ubuntu-latest
    needs: Run-Unit-Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        run: python src/train.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-artifact
          path: model_train.pkl

  Run-Inference:
    runs-on: ubuntu-latest
    needs: Train-Model
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: model-artifact
          path: .

      - name: Run inference script
        run: python src/inference.py